name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build 
      
    - name: Getting apk ready
      run: echo -e '\\033[1;38;5;46mBuilding APK'
    - uses: actions/upload-artifact@v2
      with:
        name: action done
        path: |
          ./app/build/outputs/apk/debug/app-debug.apk
          ./app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Listing dir
      run: ls -a ./app/build/outputs/apk/debug && echo "" && ls -a ./app/build/outputs/apk/release
